name:  Bug Report
description: Reportar un problema o error en SearchMind
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Gracias por reportar este bug. Por favor, completa la siguiente informaci贸n para ayudarnos a resolverlo.

  - type: input
    id: version
    attributes:
      label: Versi贸n
      description: 驴Qu茅 versi贸n de SearchMind est谩s usando?
      placeholder: "v1.0.0"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Entorno
      description: 驴D贸nde est谩 ocurriendo el problema?
      options:
        - Docker (Recomendado)
        - Desarrollo Local
        - Producci贸n
        - Otro
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descripci贸n del Problema
      description: Descripci贸n clara y concisa del problema
      placeholder: El sistema falla cuando...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Pasos para Reproducir
      description: Pasos detallados para reproducir el error
      placeholder: |
        1. Ir a...
        2. Hacer clic en...
        3. Ver error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamiento Esperado
      description: 驴Qu茅 esperabas que sucediera?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportamiento Actual
      description: 驴Qu茅 est谩 sucediendo en su lugar?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs y Errores
      description: Copia cualquier log relevante o mensaje de error
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Agrega screenshots si ayudan a explicar el problema

  - type: textarea
    id: additional
    attributes:
      label: Informaci贸n Adicional
      description: Cualquier otra informaci贸n relevante

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: He buscado issues similares existentes
          required: true
        - label: He le铆do la documentaci贸n
          required: true
        - label: Este bug es reproducible
          required: true